[build-system]
requires = ["setuptools", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
name = "settings-action"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["click"]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "coverage==7.15.2",
  "mypy==2.3.0",
  "mypy-extensions==1.1.0",
  "pytest-cov==7.1.0",
  "types-requests==2.33.0.20260712",
  "validate-pyproject==0.25",
  "fastjsonschema<2.22",
]

[tool.setuptools-git-versioning]
enabled = true

[tool.ruff]
line-length = 80

[tool.pytest.ini_options]
addopts = [
  "test.py",
  "--verbose",
  "--cov=main",
  "--capture=no",
  "--cov-report=term-missing",
]
